[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "xplainable"
version = "0.1.2"
authors = [
  { name="xplainable pty ltd", email="contact@xplainable.io" },
]
description = "The ai engine for business optimisation, innovation, and decision making"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
