[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "xplainable"
version = "1.0.5"
authors = [
  { name="xplainable pty ltd", email="contact@xplainable.io" },
]
description = "Real-time explainable machine learning for business optimisation"
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"

classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
]

dependencies = [
        "drawsvg>=2.1.1",
        "hyperopt>=0.2.7",
        "ipywidgets>=8.0.5",
        "keyring>=23.2.1",
        "matplotlib>=3.4.2",
        "altair>=5.0.1",
        "numba>=0.56.4",
        "numpy>=1.20.3,<=1.23.5",
        "pandas>=1.5.2,<=1.9.0",
        "pyperclip>=1.8.2",
        "requests",
        "scikit_learn>=1.2.2",
        "scipy>=1.6.2",
        "seaborn>=0.11.1",
        "traitlets>=5.5.0",
        "urllib3>=1.26.5",
        "psutil>=5.9.4",
        "joblib>=1.2.0",
        "tornado==6.1",
        "jupyter-client==7.3.2"
    ]