name: Xplainable Docs CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx

      - name: Generate Sphinx Documentation
        run: |
          cd docs
          make html

      - name: Upload Docs to DigitalOcean Spaces
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.ACCESS_KEY }}
          secret_key: ${{ secrets.SECRET_KEY }}
          space_name: xplainable-docs
          space_region: syd1
          source: docs/_build/html  # replace with the correct path to your sphinx build
          permission: public-read
